const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let content,current=Number(localStorage.getItem('jotrip.chapter')||0),soundOn=localStorage.getItem('jotrip.sound')!=='off',lastFocus=null;
const root=$('#sheetRoot'), sheet=$('#storySheet'), reader=$('#reader');
async function loadContent(){const base=await fetch('/content.json',{cache:'no-store'}).then(r=>r.json());try{const local=JSON.parse(localStorage.getItem('jotrip.content.override')||'null');content=local?deepMerge(base,local):base}catch{content=base}applyCopy();renderChapter(current);buildChapterMenu()}
function deepMerge(a,b){if(Array.isArray(a)||Array.isArray(b))return b??a;if(a&&typeof a==='object'&&b&&typeof b==='object'){const o={...a};for(const k of Object.keys(b))o[k]=k in a?deepMerge(a[k],b[k]):b[k];return o}return b??a}
function applyCopy(){$('#roomEyebrow').textContent=content.room.eyebrow;$('#roomEntry').textContent=content.room.entry;$('#roomHint').textContent=content.room.hint;$('#islandLink').textContent=content.room.islandLink;$('#roomFooter').textContent=content.footer}

class RoomSound{constructor(){this.ctx=null;this.master=null;this.ambient=null}ensure(){if(!soundOn)return null;if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.2;this.master.connect(this.ctx.destination)}if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx}noise(sec=.16,filter=1800,gain=.15){const c=this.ensure();if(!c)return;const len=Math.floor(c.sampleRate*sec),buf=c.createBuffer(1,len,c.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();f.type='lowpass';f.frequency.value=filter;g.gain.value=gain;s.buffer=buf;s.connect(f);f.connect(g);g.connect(this.master);s.start()}paper(){this.noise(.22,2500,.22)}photo(){this.noise(.10,3300,.15)}window(){const c=this.ensure();if(!c)return;this.noise(.55,850,.16);const o=c.createOscillator(),g=c.createGain();o.frequency.value=128;g.gain.setValueAtTime(.02,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.18);o.connect(g);g.connect(this.master);o.start();o.stop(c.currentTime+.2)}book(){const c=this.ensure();if(!c)return;this.noise(.32,1600,.22);const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=78;g.gain.setValueAtTime(.045,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.24);o.connect(g);g.connect(this.master);o.start();o.stop(c.currentTime+.25)}}
const sounds=new RoomSound();$('#soundToggle').setAttribute('aria-pressed',String(soundOn));$('#soundToggle').addEventListener('click',()=>{soundOn=!soundOn;localStorage.setItem('jotrip.sound',soundOn?'on':'off');$('#soundToggle').setAttribute('aria-pressed',String(soundOn));if(soundOn)sounds.paper()});

function closeMenu(){$('#menu').hidden=true;$('#menuToggle').setAttribute('aria-expanded','false')}$('#menuToggle').addEventListener('click',()=>{const m=$('#menu');m.hidden=!m.hidden;$('#menuToggle').setAttribute('aria-expanded',String(!m.hidden));if(!m.hidden)sounds.paper()});
$$('[data-action]').forEach(el=>el.addEventListener('click',()=>{closeMenu();act(el.dataset.action)}));
function act(a){if(a==='book')return openBook();if(a==='welcome')return openSheet(welcomeMarkup(),'paper');if(a==='drink')return openSheet(drinkMarkup(),'photo');if(a==='memories')return openSheet(memoriesMarkup(),'photo',bindMemories);if(a==='window')return openSheet(windowMarkup(),'window');if(a==='planner')return openSheet(plannerMarkup(),'paper',bindPlanner)}
function openSheet(markup,sound='paper',bind){lastFocus=document.activeElement;sheet.innerHTML=`<button class="close-sheet" type="button" aria-label="Đóng">×</button>${markup}`;root.hidden=false;sheet.querySelector('.close-sheet').addEventListener('click',closeSheet);if(bind)bind();sounds[sound]?.();sheet.querySelector('.close-sheet').focus()}
function closeSheet(){root.hidden=true;sheet.innerHTML='';lastFocus?.focus?.()}root.addEventListener('click',e=>{if(e.target.matches('[data-close]'))closeSheet()});
function welcomeMarkup(){return `<p class="kicker">A LETTER FROM PHÚ QUỐC</p><div class="welcome-paper"><h2>${esc(content.welcome.title)}</h2><p>${esc(content.welcome.body)}</p><small>${esc(content.welcome.sign)}</small></div>`}
function drinkMarkup(){return `<p class="kicker">THE WELCOME TABLE</p><h2>${esc(content.drink.title)}</h2><div class="drink-note"><div class="drink-glass" aria-hidden="true">◌</div><p>${esc(content.drink.body)}</p></div>`}
function memoriesMarkup(){return `<p class="kicker">REAL MOMENTS · JOTRIP ARCHIVE</p><h2>${esc(content.memories.title)}</h2><p>${esc(content.memories.intro)}</p><div class="memory-grid">${content.memories.items.map((m,i)=>`<button class="memory-card" data-memory="${i}" type="button"><img src="/assets/${m.img}" alt="Ảnh tư liệu thực tế JoTrip" loading="lazy"><span>${esc(m.caption)}</span></button>`).join('')}</div><div class="loose-notes">${(content.memories.notes||[]).map(n=>`<blockquote>${esc(n)}</blockquote>`).join('')}</div>`}
function bindMemories(){$$('[data-memory]').forEach(b=>b.addEventListener('click',()=>{const m=content.memories.items[Number(b.dataset.memory)];sounds.photo();sheet.innerHTML=`<button class="close-sheet" type="button" aria-label="Đóng">×</button><p class="kicker">MỘT KÝ ỨC TRÊN BÀN</p><div class="memory-focus"><img src="/assets/${m.img}" alt="Ảnh tư liệu thực tế JoTrip"><div><h2>${esc(m.caption)}</h2><p>Ảnh thật trong kho tư liệu JoTrip tại Phú Quốc. Chúng tôi chỉ kể thêm câu chuyện cụ thể khi có đủ bối cảnh để không biến một khoảnh khắc thật thành lời quảng cáo được dựng lại.</p><button class="secondary" id="backMemories" type="button">← Xem những tấm khác</button></div></div>`;sheet.querySelector('.close-sheet').addEventListener('click',closeSheet);$('#backMemories').addEventListener('click',()=>{sheet.innerHTML=`<button class="close-sheet" type="button" aria-label="Đóng">×</button>${memoriesMarkup()}`;sheet.querySelector('.close-sheet').addEventListener('click',closeSheet);bindMemories()})}))}
function windowMarkup(){return `<p class="kicker">A QUIET VIEW</p><h2>${esc(content.window.title)}</h2><div class="window-view"><p>${esc(content.window.body)}</p></div>`}
function plannerMarkup(){return `<p class="kicker">JOTRIP DMC · TRAVEL BRIEF</p><h2>${esc(content.planner.title)}</h2><p class="planner-intro">${esc(content.planner.intro)}</p><div class="planner-note">${esc(content.planner.note)}</div><form class="planner-form" id="plannerForm">
<section class="form-section"><h3>01 · Bạn đi cùng ai?</h3><div class="field-grid"><label class="field">Tên của bạn<input name="name" autocomplete="name"></label><label class="field">Nhóm của bạn<select name="group"><option value="">Chọn nếu muốn</option><option>Hai người</option><option>Gia đình</option><option>Nhiều thế hệ</option><option>Nhóm bạn</option><option>Đoàn doanh nghiệp</option><option>Khác</option></select></label><label class="field">Người lớn<input name="adults" type="number" min="1" inputmode="numeric" placeholder="2"></label><label class="field">Trẻ em và độ tuổi<input name="children" placeholder="Ví dụ: 2 bé - 5 và 9 tuổi"></label></div></section>
<section class="form-section"><h3>02 · Khi nào bạn đến?</h3><div class="field-grid"><label class="field">Ngày / khoảng thời gian<input name="dates" placeholder="Ví dụ: 18-23/12"></label><label class="field">Số đêm<input name="nights" type="number" min="1" inputmode="numeric"></label><label class="field">Nơi ở dự kiến<input name="hotel" placeholder="Resort / khu vực / chưa chọn"></label><label class="field">Tình trạng lưu trú<select name="hotelStatus"><option>Chưa đặt</option><option>Đã đặt</option><option>Muốn JoTrip cùng chọn</option></select></label></div></section>
<section class="form-section"><h3>03 · Bạn muốn những ngày ở đảo trôi qua thế nào?</h3><div class="checks">${['Đi biển','Thư thả','Ẩm thực','Riêng tư','Gia đình & trẻ em','Hiểu Phú Quốc','Dịp đặc biệt','Nghỉ dưỡng','Câu cá','Chưa biết - hãy gợi ý'].map(x=>`<label class="check"><input type="checkbox" name="interest" value="${x}"><span>${x}</span></label>`).join('')}</div></section>
<section class="form-section"><h3>04 · JoTrip nên chăm phần nào?</h3><div class="checks">${['Đón sân bay','Xe riêng','Lưu trú','Trải nghiệm riêng','Ăn uống','Vé & show','Ngày biển','Điều phối cả kỳ nghỉ','Phương án khi thời tiết đổi'].map(x=>`<label class="check"><input type="checkbox" name="service" value="${x}"><span>${x}</span></label>`).join('')}</div></section>
<section class="form-section"><h3>05 · Điều gì quan trọng với bạn?</h3><div class="field-grid"><label class="field">Dịp đặc biệt<input name="occasion" placeholder="Sinh nhật, kỷ niệm, cầu hôn..."></label><label class="field">Nhịp kỳ nghỉ<select name="pace"><option>Thật chậm</option><option>Cân bằng</option><option>Khám phá nhiều</option><option>Chưa rõ</option></select></label><label class="field" style="grid-column:1/-1">Có điều gì chúng tôi nên biết để chăm bạn tốt hơn?<textarea name="careNotes" placeholder="Khả năng di chuyển, khẩu vị, điều cần tránh, người lớn tuổi, trẻ nhỏ, sở thích riêng..."></textarea></label></div></section>
<section class="form-section"><h3>06 · Để chúng tôi liên hệ lại</h3><div class="field-grid"><label class="field">Email / điện thoại / WhatsApp<input name="contact" required autocomplete="email"></label><label class="field">Cách bạn muốn được liên hệ<select name="channel"><option>Email</option><option>WhatsApp</option><option>Điện thoại</option><option>Zalo</option></select></label></div></section>
<div class="planner-actions"><p>Bản nháp được lưu trên thiết bị này. Khi gửi, bạn sẽ được xem lại email trước khi quyết định gửi đi.</p><div><button class="secondary" type="button" id="saveDraft">Lưu bản nháp</button> <button class="primary" type="submit">Đặt tờ brief lên bàn ↗</button></div></div></form>`}
function bindPlanner(){const f=$('#plannerForm'),saved=JSON.parse(localStorage.getItem('jotrip.brief')||'{}');for(const [k,v] of Object.entries(saved)){const el=f.elements[k];if(!el)continue;if(el instanceof RadioNodeList){[...el].forEach(x=>x.checked=(Array.isArray(v)?v:[v]).includes(x.value))}else el.value=v}$('#saveDraft').addEventListener('click',()=>{saveBrief(f);sounds.paper();$('#saveDraft').textContent='Đã lưu trên máy'});f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const data=saveBrief(f),summary=briefSummary(data);sounds.paper();sheet.innerHTML=`<button class="close-sheet" type="button" aria-label="Đóng">×</button><p class="kicker">YOUR PHU QUOC JOURNEY · DRAFT 01</p><div class="journey-folder"><small>JOTRIP DMC · TRAVEL, MADE PERSONAL.</small><h3>Một bản nháp cho chuyến đi của bạn.</h3><pre>${esc(summary)}</pre><p>Chúng tôi chưa xem được bản nháp này cho đến khi bạn chủ động gửi email. Bạn có thể đọc lại trước khi gửi.</p><button class="primary" id="sendBrief" type="button">Mở email để gửi JoTrip ↗</button></div>`;sheet.querySelector('.close-sheet').addEventListener('click',closeSheet);$('#sendBrief').addEventListener('click',()=>location.href='mailto:phuquoclux@gmail.com?subject='+encodeURIComponent('JoTrip DMC - Phu Quoc Journey Draft 01')+'&body='+encodeURIComponent(summary))})}
function saveBrief(f){const d=new FormData(f),o={};for(const [k,v] of d){if(o[k])o[k]=[].concat(o[k],v);else o[k]=v}localStorage.setItem('jotrip.brief',JSON.stringify(o));return o}
function briefSummary(d){const list=v=>Array.isArray(v)?v.join(', '):(v||'Chưa ghi');return ['Xin chào JoTrip DMC,','','Tôi muốn trao đổi về một chuyến đi tại Phú Quốc.','','Tên: '+list(d.name),'Đi cùng: '+list(d.group),'Số khách: '+list(d.adults)+' người lớn; '+list(d.children),'Thời gian: '+list(d.dates),'Số đêm: '+list(d.nights),'Lưu trú: '+list(d.hotel)+' - '+list(d.hotelStatus),'Quan tâm: '+list(d.interest),'Nhịp nghỉ: '+list(d.pace),'Dịch vụ muốn JoTrip hỗ trợ: '+list(d.service),'Dịp đặc biệt: '+list(d.occasion),'Điều JoTrip nên biết: '+list(d.careNotes),'Liên hệ: '+list(d.contact)+' - '+list(d.channel),'','Tôi chủ động gửi các thông tin trên để JoTrip hiểu nhu cầu và liên hệ tư vấn.'].join('\n')}

function buildChapterMenu(){const nav=$('#chapterMenu');nav.innerHTML=content.chapters.map((c,i)=>`<button type="button" data-chapter="${i}">${String(i+1).padStart(2,'0')} · ${esc(c.title)}</button>`).join('');$$('[data-chapter]').forEach(b=>b.addEventListener('click',()=>{switchChapter(Number(b.dataset.chapter));nav.hidden=true}))}
function openBook(){lastFocus=document.activeElement;reader.hidden=false;renderChapter(current);sounds.book();$('#readerClose').focus()}function closeBook(){reader.hidden=true;localStorage.setItem('jotrip.chapter',String(current));lastFocus?.focus?.()}$('#readerClose').addEventListener('click',closeBook);$('#chapterMenuToggle').addEventListener('click',()=>$('#chapterMenu').hidden=!$('#chapterMenu').hidden);
function renderChapter(n){if(!content)return;current=Math.max(0,Math.min(n,content.chapters.length-1));const c=content.chapters[current];$('#chapterNo').textContent='CHƯƠNG '+String(current+1).padStart(2,'0');$('#chapterOrigin').textContent=c.origin;$('#chapterTitle').innerHTML=esc(c.title).replace(/(Phú Quốc Lux|đã qua|hôm nay|theo cách riêng|đồng hành|là của bạn)/,'<em>$1</em>');$('#chapterSub').textContent=c.sub;$('#chapterBody').textContent=c.body;$('#chapterImage').src='/assets/'+c.img+'-1600.webp';$('#chapterImage').alt=c.caption;$('#chapterCaption').textContent=c.caption;$('#chapterCount').textContent=String(current+1).padStart(2,'0')+' / '+String(content.chapters.length).padStart(2,'0');$('#prevChapter').disabled=current===0;$('#nextChapter').disabled=current===content.chapters.length-1;$('#chapterNextStory').textContent=current===content.chapters.length-1?'Kể JoTrip về chuyến đi ↗':'Đọc chương tiếp →'}
let switching=false;function switchChapter(n){if(switching||n<0||n>=content.chapters.length||n===current)return;if(matchMedia('(max-width:700px)').matches||matchMedia('(prefers-reduced-motion:reduce)').matches){renderChapter(n);reader.scrollTo({top:0,behavior:'smooth'});sounds.paper();return}switching=true;const t=$('#turnSheet');t.classList.remove('turning');void t.offsetWidth;t.classList.add('turning');sounds.paper();setTimeout(()=>renderChapter(n),330);setTimeout(()=>{t.classList.remove('turning');switching=false},790)}$('#prevChapter').addEventListener('click',()=>switchChapter(current-1));$('#nextChapter').addEventListener('click',()=>switchChapter(current+1));$('#chapterNextStory').addEventListener('click',()=>{if(current===content.chapters.length-1){closeBook();setTimeout(()=>act('planner'),120)}else switchChapter(current+1)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!root.hidden)closeSheet();else if(!reader.hidden)closeBook();else closeMenu();return}if(!reader.hidden&&!e.target.matches('input,textarea,select')){if(e.key==='ArrowRight')switchChapter(current+1);if(e.key==='ArrowLeft')switchChapter(current-1)}});let sx=0;$('#physicalBook').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('#physicalBook').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>60)switchChapter(current+(dx<0?1:-1))},{passive:true});
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
loadContent();
