import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
const BASE='http://127.0.0.1:8877/jotrip-dmc/';
await mkdir('qa-artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const errors=[];
try{
 const desktop=await browser.newPage({viewport:{width:1536,height:864},deviceScaleFactor:1});
 desktop.on('pageerror',e=>errors.push('desktop '+e.message));
 desktop.on('response',r=>{if(r.status()>=400)errors.push('desktop HTTP '+r.status()+' '+r.url())});
 await desktop.goto(BASE,{waitUntil:'networkidle',timeout:30000});
 await desktop.locator('.scene-master').waitFor({state:'visible'});
 const sceneOk=await desktop.locator('.scene-master').evaluate(e=>e.complete&&e.naturalWidth===1536);
 const photoOk=await desktop.locator('.airport-embed img').evaluate(e=>e.complete&&e.naturalWidth>0);
 const stylesOk=await desktop.locator('.scene').evaluate(e=>getComputedStyle(e).position==='absolute');
 if(!sceneOk||!photoOk||!stylesOk)throw Error('Desktop failed asset/render validation '+JSON.stringify({sceneOk,photoOk,stylesOk}));
 await desktop.screenshot({path:'qa-artifacts/approved-desktop.png'});
 await desktop.locator('.book-story-live').click();
 await desktop.locator('#readerDialog[open]').waitFor();
 if(!/Hòn đảo trong chúng tôi/.test(await desktop.locator('#chapterTitle').innerText()))throw Error('Reader content missing');
 await desktop.locator('#readerDialog [data-close]').click();
 await desktop.locator('[data-lang="en"]').first().click();
 if(!/Travel with people who call it home/.test(await desktop.locator('#heroLine1').innerText()))throw Error('Desktop locale switch failed');
 if(!/The island/.test(await desktop.locator('#bookTitle1').innerText()))throw Error('Book locale switch failed');
 await desktop.screenshot({path:'qa-artifacts/phase1-desktop-en.png'});
 await desktop.locator('[data-lang="vi"]').first().click();
 await desktop.locator('.book-story-live').click();
 await desktop.locator('#readerDialog[open]').waitFor();
 await desktop.screenshot({path:'qa-artifacts/approved-reader.png'});
 await desktop.locator('#readerDialog [data-close]').click();
 const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 mobile.on('pageerror',e=>errors.push('mobile '+e.message));
 mobile.on('response',r=>{if(r.status()>=400)errors.push('mobile HTTP '+r.status()+' '+r.url())});
 await mobile.goto(BASE,{waitUntil:'networkidle',timeout:30000});
 const mobileVisible=await mobile.locator('.mobile-stage').isVisible();
 const desktopHidden=await mobile.locator('.desktop-stage').isHidden();
 if(!mobileVisible||!desktopHidden)throw Error('Mobile breakpoint/camera failed');
 await mobile.screenshot({path:'qa-artifacts/approved-mobile.png',fullPage:true});
 await mobile.locator('[data-lang="en"]').first().click();
 if(!/Travel with people who call it home/.test(await mobile.locator('#mobileHero1').innerText()))throw Error('Mobile locale switch failed');
 if(!/Tap to open the book/.test(await mobile.locator('#mobileBookCue').innerText()))throw Error('Mobile click cue missing');
 await mobile.screenshot({path:'qa-artifacts/phase1-mobile-en.png',fullPage:true});
 await mobile.locator('[data-lang="vi"]').first().click();
 await mobile.locator('.mobile-actions button').click();
 await mobile.locator('#briefDialog[open]').waitFor();
 await mobile.locator('[name="name"]').fill('Demo QA');
 await mobile.locator('#briefForm button[type="submit"]').click();
 if(!/chưa nhận được/.test(await mobile.locator('#briefResult').innerText()))throw Error('Draft disclaimer missing');
 if(errors.length)throw Error('Browser network/runtime errors: '+errors.join('; '));
 console.log('PASS Phase1: immutable scene asset, live VI/EN hero+book, cues, reader, 390 mobile, local draft, zero missing resources');
}finally{await browser.close()}
